export const quizTypes = {
  ADD_QUESTION_SUCCESS: "ADD_QUESTION_SUCCESS",
  ADD_QUESTION_FAIL: "ADD_QUESTION_FAIL",
  NEXT_QUESTION: "NEXT_QUESTION",
  SUBMIT_QUESTION: "SUBMIT_QUESTION",
  SELECT_QUESTION: "SELECT_QUESTION",
}
