export const quizTypes = {
  ADD_QUESTION_SUCCESS: "ADD_QUESTION_SUCCESS",
  ADD_QUESTION_FAIL: "ADD_QUESTION_FAIL",

  SELECT_CATEGORY: " SELECT_CATEGORY",

  SELECT_QUESTION: "SELECT_QUESTION",
  NEXT_QUESTION: "NEXT_QUESTION",
  SUBMIT_QUESTION: "SUBMIT_QUESTION",
  CHECK_QUESTION: "CHECK_QUESTION",
  RESET_GAME: "RESET_GAME",
}
